modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
[[mods]]
modId="wallpapers"
displayName="Wallpapers"
version="0.9a-1.20.1"
logoFile="wallpapers_logo.png"
authors="Maker,s Mods"
credits="Im_Maker"
description='''
Adds new colorful building blocks called Wallpaper Blocks!
'''
[[dependencies.wallpapers]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.wallpapers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.20.2)"
    ordering="NONE"
    side="BOTH"
